source 'https://rubygems.org'

gem 'middleman', '~> 4.2'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'middleman-sprockets'
gem "sprockets", ">= 3.7.2"
gem "ffi", ">= 1.9.24"
gem 'middleman-deploy', git: 'https://github.com/lewagon/middleman-deploy.git'
gem 'pry-byebug', require: true

# Assets
gem 'font-awesome-middleman'
gem "bootstrap-sass", ">= 3.4.1"
gem 'jquery-middleman'


